### ISSUE TITLE
Change "police lights" on keyboard from "blue / red" to "blue / blue" everywhere 

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-user-guide#110]
Sis is se sherman Police shpeaking! Police lights on the MEGA65 keyboard are no longer blue and red! They are blue / blue now (weil des korrekt is) once you flashed the latest CPLD (keyboard) firmware. Please change accordingly throughout the manual.

**Comment by Edilbert** [comment]
:-)

**Comment by isedwards** [comment]
Is *ambulance mode* in "[understanding the core booting process](https://github.com/MEGA65/mega65-user-guide/blob/3c6fe90e5e8fd424a4f6bd4bb8ecea3058393538/cores-and-flashing.tex#L190-L200)" the same as *police mode* in the appendices ([here](https://github.com/MEGA65/mega65-user-guide/blob/3c6fe90e5e8fd424a4f6bd4bb8ecea3058393538/appendix-mega65r2-flashing.tex#L199-L202) and [here](https://github.com/MEGA65/mega65-user-guide/blob/3c6fe90e5e8fd424a4f6bd4bb8ecea3058393538/appendix-mega65r2-flashing.tex#L393-L395))?

If so, it may make sense to stick with *ambulance mode* due to the description of the machine needing "first-aid".

**Comment by gardners** [comment]
Correct. It should be "ambulance mode" everywhere.
Feel free to make a pull request with the change.

**Comment by isedwards** [comment]
@gardners can you also confirm @deftmega's change from flashing red and blue to just flashing blue?

Presumably you guys have both red and blue lights on emergency vehicles?

**Comment by gardners** [comment]
Yes, only blue now. Its actually to work around a problem with current backflow from HDMI into the keyboard. Voltage is enough to trigger the red LEDs, but not the blue ones.  So the red ones were blinking when computer off, but HDMI connected to a monitor that was on. By making it only blink blue, nothing appears, because the critical voltage for the blue LEDs is higher.
