### ISSUE TITLE
Some anomalies on GS opcode descriptions

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-user-guide#122]
Continuing the travel ( see #121 ) over GS specific opcodes ... I've found these kinds of problems so far.

## 8 bit look description of 32 bit opcodes

I often see manual talks about "bit 7" and "> 255" which are clearly meant for 8 bit operations. However in case of "Q" stuffs, it must be 32 bit, thus the description should be modified.

## BITQ

BITQ is documented as a shift operation. I would assume, it's a bug, as it should be the 32 bit version of the BIT 6502 opcode, which is nothing to do with shift.

## ORQ #$nn should not exist!

Also, it seems, there is an other kind of single problem, listing this opcode:

    No description ORQ #$nn 42 42 09

I believe this is an error, no immediate addressing opcode should be in the "Q" series of GS opcodes. Also the "no description" title makes it suspect, it's just a mistake to include this in the list? Btw this is even in file ./instruction_sets/45GS02.opc maybe the doc is generated from there?

**Comment by Edilbert** [comment]
I fixed the ORQ and LDQ descriptions, removing the not existent address modes.
The changes may not show up in the pdf file immediately, because the makefile does not monitor changes in the files inside the instruction_sets directory. You can force the update by deleting the file "instructionset-45GS02.tex" before doing the make. This will trigger the creation of an updated file "instructionset-45GS02.tex".

**Comment by Edilbert** [comment]
The description for BITQ was missing, so the ASRQ description was falsely repeated in the BITQ box.
The correct description is now added.
