### ISSUE TITLE
Legal and unintended opcodes may be hard to distinguish for red/blue colour blind readers

### ISSUE THREAD

**Issue by LAK132** [MEGA65/mega65-user-guide#141]
The `Official And Unintended Instructions` section of the chipset reference uses red and blue to distinguish unintended and legal opcodes respectively. This may be hard for red/blue colour blind people to see.

**Comment by Edilbert** [comment]
AFAIK there exists red/green colour blindness or blue/yellow colour blindness.
I've never heard, that a red/blue colour blindness exists.
But I wanted to suggest anyhow, that we remove the unintended opcodes from the chapter.
The MEGA65 does not support these opcodes and so listing these leads to confusion instead of information.

**Comment by gardners** [comment]
Actually we do already support a lot of them, and will have complete support in time.

So red/blue colourblindness can occur for monochromats and some bichromats, for whom both may appear black.  The solution is to use, say, orange and blue, so that there is red and green in the non-blue colour, which makes it more likely to be able to be discriminated. It doesn't need a lot of green in the red to do this. But I would probably go for something like the Amiga orange, myself.

(Incidentally, yellow and blue is the colour pair that apart from black and white is most easily discriminated for almost all kinds of colour blindness.)

**Comment by LAK132** [comment]
I think it would be wise to additionally include a small symbol along side the unintended opcodes so that this distinction doesn't rely *entirely* on colour

**Comment by gardners** [comment]
I'd be totally comfortable with that. Or put them in italic or some other typeface perhaps?
