### ISSUE TITLE
Document selecting 1351 driver in GEOS

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#142]
From Discord:

adtbmheute um 13:18 Uhr
OK,

How to install the 1351 as default mouse in GEOS for the MEGA65.
(1351 in port 1)

- start GEOS from D81.
- press F1
- select folder INPUT.drv by pressing MEGA & 8
- follow the rest of the instructions in the attached picture until:

"...Um als default zu wählen...."
- to make it default input driver, you have to drag&drop the driver over the joystickdriver.
so you first install the driver and then you replace the default joystick.
(PS: i have to report, that the mouse would need some timing rework @gardners in GEOS, it's not comparable to the 1351 in Solitäire at all)
(i would say: jumpy....)
(latest bitstream, latest ROM, R3)

**Comment by dansanderson** [comment]
Per bluewaysw_falk, the current version of GEOS installs the 1351 mouse driver by default. It sounds like the GEOS65 project might benefit from a way to select the initial input driver prior to running it, or some kind of keyboard selection of pointer control driver. (One user reported not owning a mouse and getting stuck by the new default.)

I'm resolving this because GEOS65 documentation is out of scope for mega65-user-guide. I'd be curious to know if it was historically considered in scope, but there isn't any GEOS65 documentation here today, and it seems like it ought to have its own project-specific documentation.
