### ISSUE TITLE
DEF basic example

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#158]
Syntax error in 70 (?)

70 PRINT USING " ##.##";FNSD(D)

ROM 920151

**Comment by Edilbert** [comment]
The listing in the manual is correct, but you had a typo in line 30, the definition of FNSD(X):
Manual: 30 DEF FN SD(X)= SIN(X*PD): REM SIN FOR DEGREES
Yours:    30 DEF FN SD(X)= SIN(X*PD); REM SIN FOR DEGREES
There was a semicolon instead of a colon.
The error message tells at line of error the line, where the function is called, not the definition line, so this information is sometimes misleading.
