### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MJoergen** [MEGA65/mega65-user-guide#166]
On page 30 there is a link to "https://github.com/mega65/mega65-files", but this link is broken. I could not find the correct link.

The link is placed in line 140 of the file configuring.tex.

I'm using the following version:
commit a2964b0292f646e137e62535737fa5799c77756b
Date: Tue Jan 12 18:14:21 2021 +1030

**Comment by gardners** [comment]
Ah, yes. You would be quite right.  That needs correcting to point somewhere more sensible.
If you need the files in the meantime, we can get them to you, but we need to think about where we point that page to.

**Comment by gurcei** [comment]
On the latest master, I've merged a commit that elaborated on where to locate the latest support files on the new filehost.

I put that information in "CHAPTER 10 - Using a Nexys4DDR as a MEGA65" - subsection: "Preparing microSDHC card".

Though since the link you mentioned comes from an even earlier chapter, "CHAPTER 4 - Configuring your MEGA65" - subsection: "Installing ROM and Other Support Files", I'm now starting to wonder whether I should move some of these details from chapter 10 into chapter 4, and let chapter 10 reference back to them.

Will give this some more thought later, as I slowly get more familiar with where different topics are located in the book and more sensitive to where the overlaps are.

But it's interesting that the

**Comment by gurcei** [comment]
Ok, this has been resolved in the latest mega65-book.

More detailed information has been provided on how to retrieve support files from the new filehost in "CH4: Configuring your MEGA65" in the "Installing ROM and Other Support Files" section.
