### ISSUE TITLE
BASIC example CHAR, incorrect x-coordinate

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#205]
1. Example CHAR 304,x,x,x,x does not print in the middle of the screen. Replace 304 by 39.
2. I cannot check myself, but since you worked on memory locations, is "$29800" still OK?

ps, I made a little BASIC example for CHAR. I will put it on the D81

**Comment by gurcei** [comment]
Wow, this command seems to have an odd mix of **column** param specified in char-units (0-39, or 0-79), and **row** param specified in pixel-units.

So I agree with you on point 1 that it ought to have a value like 39, and perhaps I should clarify the need for that parameter to be in char-units and not pixel units, as it didn't seem quite clear in the text to me.

On point 2, I see the kernal source position character sets at these locations:
```
$2,9000-$2,9FFF : CHAR A
$2,D000-$2,DFFF : CHAR C
$3,D000-$3,DFFF : CHAR B
```

So giving these a try with a quick example:
```
10 SCREEN 640,400,2
20 X=20:Y=100
30 CHAR X,Y,2,2,2,"CHAR A UPPER : {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$29000:Y=Y+20
40 CHAR X,Y,2,2,2,"CHAR A LOWER : {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$29800:Y=Y+20
50 CHAR X,Y,2,2,2,"CHAR C UPPER : {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$2D000:Y=Y+20
60 CHAR X,Y,2,2,2,"CHAR C LOWER : {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$2D800:Y=Y+20
70 CHAR X,Y,2,2,2,"CHAR B UPPER : {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$3D000:Y=Y+20
80 CHAR X,Y,2,2,2,"CHAR B LOWER ; {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$3D800:Y=Y+20
90 GETKEY A$
100 SCREEN CLOSE
```
This didn't get me quite the result I hoped for:
![image](https://user-images.githubusercontent.com/20013309/132126110-875ed73a-517d-4a34-aebb-480437d6fee3.png)

Font A and C look fine, but doesn't look like it's able to access Font B for drawing.

My suspicion is that the address-parameter only accepts a 16-bit value, so font a & b were fortunate enough to be mapped into the 16-bit address space at the time of the CHAR call, but font c wasn't.

So might need @Edilbert to confirm behaviour on point 2, but I'm happy to update the example to use 39 instead of 304.

**Comment by gurcei** [comment]
Actually, I decided to improve the example and make it bigger instead 😁 
```
10 SCREEN 640,400,2
20 CHAR 28,180,4,4,2,"MEGA65",$9000
30 GETKEY A$
40 SCREEN CLOSE
```
![image](https://user-images.githubusercontent.com/20013309/132126890-5c1d8535-e58f-471f-aeb1-443a3ebc09a0.png)

**Comment by MauriceMEGA65** [comment]
I like the example!
If the manual is updated accordingly, I think we can close this ticket

**Comment by Edilbert** [comment]
The CHAR command uses still a 16 bit address for the charset.
So you must set the bank after the address.
For example instead of:
80 CHAR X,Y,2,2,2,"CHAR B LOWER ; {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$3D800
one must write
80 CHAR X,Y,2,2,2,"CHAR B LOWER ; {$5E}{$5C}{$1C}{$1F}{$5B}{$5D}",$D800,3

But I think in this case, it's better to make the CHAR command sensitive to 32 bit addresses.
I'll take care of that.

**Comment by Edilbert** [comment]
Version 920222 fixes CHAR to accept a long address for charset.
No more bank needed or allowed.

**Comment by MauriceMEGA65** [comment]
Super, thank a lot Edilbert!!

**Comment by gurcei** [comment]
Awesome, thx Edilbert! :-)
