### ISSUE TITLE
BASIC example CMD. Freezes XEMU if no printer attached

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#209]
Executing the example freezes XEMU (merger branch).
Clear that I cannot print anything because there is no printer attached, but I would expect an error, not freezing up.

**Comment by gurcei** [comment]
I had a quick debug into why it stalls at the CMD step, seem to because the rom is trying to do some IEC serial handshaking with the printer, so the stall seems to be for reasonable reasons.

As for whether the rom should have a timeout before giving up, that seems reasonable.

I was curious how c64-kernal handled the situation. Typing the same example in c64-mode results in:
```
?DEVICE NOT PRESENT  ERROR
READY.
```

I'm not familiar with the distinction in behaviour with the 65 and 64 kernals, so it's something we can dig into later.

**Comment by gurcei** [comment]
Oh, I just tried the example on devkit with original rom, c65-mode and saw the error:
```
?DEVICE NOT PRESENT  ERROR
READY.
```

On the newer roms, there isn't an error, seems to work, though I need to type `CLOSE 1` twice before it gets back to the `READY.` prompt.

So if this is a problem unique to xemu (and not so much on hardware) then perhaps it's best we put it on @lgblgblgb 's radar for something to assess in xemu, and I'll close it here.

**Comment by lgblgblgb** [comment]
Honestly, I have no idea how the ROM tries to establish IEC transfers. Xemu does not emulate anything from the IEC part of the things. IIRC, once I modified some default CIA values so it does not hang, and it seems to work in C64 mode what I mostly tested (since I know that better from childhood experience ...). I don't know why "C65 mode" is different. Probably Bit shifter can answer?

**Comment by lgblgblgb** [comment]
But really I have no idea why this issue is here (even if it's closed now), it's much like an Xemu issue for me. Though since Xemu does not emulate IEC bus, it's a kind of interesting situation.
