### ISSUE TITLE
BASIC example PAINT, result in black screen

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#228]
I can get it to work, but the standard listing as in the manual gives me a black screen.
I would like your improvements in the manual as some commands have been changed.

**Comment by gurcei** [comment]
Yep, I'm experiencing the same on my end.

I had a quick debug foray into the source. It seems like the paint/fill algorithm gets stuck in some endless loop of trying to fill, perhaps due to looking for an edge to clip against but not finding one (as we had black lines drawn on a black background, at present.

Anyways, I'm a bit out of my depth in debugging it at present, so for now, I'll just remedy the example with a similar fix to what you suggested in #229 (of using PEN to enforce the colour choice).

I've also improved the wording of the PEN command docs, to clarify the optional first parameter.
