### ISSUE TITLE
BASIC example PALETTE

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#229]
Same as PAINT, result is a black screen (with green border in this case)
I can get it to work by adding PEN, but not sure if that should be needed, therefore I would like your input.

**Comment by gurcei** [comment]
I can confirm I got the same experience as you, I had to add `85 PEN 2` in order to get a blue triangle.

It looks like PEN defaults to the value of 0, which is set to be the colour black in this example.

I confirmed this by deleting my line 85 and running again, it then drew over the previous blue-triangle with a black triangle:
![image](https://user-images.githubusercontent.com/20013309/132046368-638ed0a0-b23e-4520-a7b2-fc3246586132.png)

Given that, I'll just inject your suggested PEN command into the example to sort this out.

**Comment by gurcei** [comment]
Hmm, I note that the PAINT command in the example did provide an optional colour index of 1 (which is our blue).

So given that, I can't say for sure why the PAINT call didn't just paint the entire screen blue.

But anyway, I'll just commit the suggested fix in.

**Comment by gurcei** [comment]
Ok, Fixed
