### ISSUE TITLE
Hardcopy User Guide: Cores and Flashing (chapter 6)

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#261]
WHAT ARE CORES
- According to the manual, 7 core lots are available. Is this still true? I’ve read on Discord we have 4 slots available?

FILE TYPES
- .bit files are referred to as ‘…can be copied onto your SD card’ (last line in table). But further in the text it’s mentioned that .cor files should be used. Bit misleading. Maybe update the text in the table.

WHERE TO DOWNLOAD
- remove nexys boards and Devkits (only focus on the production MEGA65)
- my suggestion is also to remove Vivado as a tool. Keep that info in the large manual

INSTALLING AN UPGRADE
- Where on the SD card to copy the .cor file? Root, or any directory?
- If using the external microSD card, is it possible to boot into the menu without the need of having the essential files on the microSD?
- After flashing, is there still a need to keep the .cor file on the SD? I believe not, but not sure
- If I’m not mistaken, currently a .cor cannot be flashed to a slot where the MEGA65 is booted from.

**Comment by gurcei** [comment]
## WHAT ARE CORES:

Our devkits have only 3 free cores (slot 0 is factory core).

However the final release product will have 7 free cores available (with slot 0 still factory core).

## FILE TYPES

Ah, fair call about the `.bit` file description in the table. I guess the description there is very 'nexys' centric. I will change the line to read:
```
    {\tt .bit} & {A plain bitstream file in its purest binary form.} \\
```

## WHERE TO DOWNLOAD

* nexys and devkit details have been hidden for the printed manual.
* On the mention of Vivado, I admit it'll be a mystery for newcomers, but I feel the occasional name-drop is ok. It's not a detail they need to grasp in any hurry, but at least some exposure and awareness of the term is created, and they can explore that curiosity later.

## INSTALLING AN UPGRADE

* root directory (I'll update the text to emphasise this)
* Hmm, there was a mention in Chapter 4 (section on 'formatting sd cards') of the sd card essential files being needed on the external microsd card:
![image](https://user-images.githubusercontent.com/20013309/139789290-8cb23ad3-06c1-4e18-987b-dab3788ef702.png)
Perhaps I could add a short reminder of it at this point.
* .cor files can be removed. After flashing, their contents are stored in the QSPI flash memory. I'll make a mention of this in the text.
* Ah, I also initially mistook that I can't flash to a slot that I'm currently running from. E.g., I felt like the flash-tool was running from slot 0, hence surely I wouldn't be permitted to flash to slot 0 while it was running. But actually, you can. This is because, the FPGA loads its configuration from one of these slots, but once the FPGA is configured, it no longer needs the QSPI slot for this config information. I'll ponder if any text could be added to re-assure the user of this.

**Comment by MauriceMEGA65** [comment]
About your below comment, this is VERY nice! So we can just put a new .COR on a microSD, put it in the external slot, boot into the flash menu, and install the new core!

I did not read about this new functionality on Discord. Very nice.

“I actually was mistaken in my thoughts on this, and checked on the hardware. To my surprise, wow, you can install .cor files via the external microSD slot without the need to add any 'SD Card essentials' files to it. That's quite nice, I'll try make a mention of this in the docs somewhere!”
