### ISSUE TITLE
Acknowledge petme2y.tff font usage, or choose another font.

### ISSUE THREAD

**Issue by sausagejohnson** [MEGA65/mega65-user-guide#3]
Need acknowledgements page?

**Comment by gardners** [comment]
If the font requires it, then, yes, of course we will acknowledge.

**Comment by sausagejohnson** [comment]
This is the source page for the font:
https://www.kreativekorp.com/software/fonts/c64.shtml

The readme states it as a free license and that:

1. The User may not sell copies of the Software for a fee.

1a. The User may give away copies of the Software free of charge provided this license and any documentation is included verbatim and credit is given to Kreative Korporation or Kreative Software.

2. The User may not modify, reverse-engineer, or create any derivative works of the Software.

3. Any Software carrying the following font names or variations thereof is not covered by this license and may not be used under the terms of this license: Jewel Hill, Miss Diode n Friends, This is Beckie's font!

3a. Any Software carrying a font name ending with the string "Pro CE" is not covered by this license and may not be used under the terms of this license.

4. This license becomes null and void if any of the above conditions are not met.

5. Kreative Software reserves the right to change this license at any time without notice.

**Comment by sausagejohnson** [comment]
Yes, and it's not clear what "the software" is in this case. Software carrying the font or the font itself.

I came across both the fonts you mentioned. The style64 one hints at c128 characters, but it's not the case now.

And then there's Devin Cook's font you mentioned. This is C64 sized as well. No C128 font, which is pretty much (exactly?) like the C65.

**Comment by gardners** [comment]
Ah, C128-sized as in 80-column aspect ratio?
Maybe there is a way to tell latex to change aspect ratio of fonts?

**Comment by sausagejohnson** [comment]
Yep 80 column. I'll see if the aspect can be changed on a font. If not, we'll keep this issue as a reminder to hunt for another Commodore 80 column font. 

Alternatively we can get in touch with the KreativeKorp guys and get their advice on what is possible.

**Comment by gardners** [comment]
Indeed. Or ask the guy who made the free 40 column one how hard it would be
to make an 80 column one.

**Comment by Edilbert** [comment]
I created a new font for the use in this manual and called it "mega.ttf".
So we don't need PetMe fonts anymore.
Furthermore I can expand it, e.g. make a narrower 80 column font or add more characters.
This first version is for the 95 ASCII characters only. PETSCII π is mapped to ~ 
so you have to insert the tilde character in your editor, to get a π in the 
screen output.

**Comment by sausagejohnson** [comment]
@Edilbert just wondering, do you make it from scratch or use another font as a base? We should probably acknowledge the source if so.

**Comment by sausagejohnson** [comment]
But thanks for this. Fonts have been dogging me.

**Comment by Edilbert** [comment]
@sausagejohnson I wrote a C program, that reads the image of a C= character ROM, extracts the bitmaps for the characters and writes a fontfile for bitmap fonts. I chose the "bdf" format. This can be used directly in some UNIX/Linux applications or be converted to other font formats by several font converters, like bdftopcf and many more. Then I used the program FontForge to read my bdf file, vectorize it with the plugin "autotrace" and do all the necessary adjustments and by hand.
But I plan to expand my C program, so that it can produce a ttf file. Then I could add features, like visible scan lines or produce a whole font family with different strokes and attributes, like bold italic, etc.

**Comment by sausagejohnson** [comment]
Ah that's awesome good job. I'll check it out with some of the listings. The asterisk was a headache for us before.

**Comment by Edilbert** [comment]
Thanks. The asterisk issue was not caused by the font. The \lstnewenvironment has apparently some special handling for operators like * / - and also for blanks. I solved the issue with the defintion:
literate={\*}{*}1{\-}{-}1{\/}{/}1{{\ }}{{ }}1
which tells the environment to print the characters instead of interpreting them.

**Comment by sausagejohnson** [comment]
Right. See that's the kind of LaTeX dark magic I just can't fathom.
