### ISSUE TITLE
Chapter "Screen Editor", strange reference link

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#397]
Where is the reference to page 223 suppose to link to?
There seems nothing of relevance on page 223.... Actually, the link goes to page 220....

![Screenshot 2021-10-30 at 17 12 45](https://user-images.githubusercontent.com/75681098/139538968-481b1f4c-ab37-47e5-8530-fd31e6a2a692.jpg)

**Comment by gurcei** [comment]
Aah, the hope on that occasion was to point them to these two escape sequences:
![image](https://user-images.githubusercontent.com/20013309/139583238-542c507d-3414-42ec-a0ee-e17a745604b2.png)

So I'll try update the text to be more explicit in what extra detail it wants to share, and perhaps instead of pointing them to the old escape codes (which still work), I'll point them to the new and friendlier CTRL-codes that Bit Shifter added recently:

![image](https://user-images.githubusercontent.com/20013309/139583308-32946313-f0cc-4b01-bf95-36db92782817.png)

**Comment by gurcei** [comment]
Ok, I've reworded to this now:
![image](https://user-images.githubusercontent.com/20013309/139584000-5cd797fe-efbf-4f52-bdef-326152aa9bb8.png)
