### ISSUE TITLE
Chapter Formatting SD Cards; unclear sentence

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#398]
What is the word "this" referring to?
Formatting, use SHDC, or something else?

![Screenshot 2021-10-30 at 17 20 55](https://user-images.githubusercontent.com/75681098/139539348-37381bd5-d35c-475e-be9d-02819767c9ea.jpg)

**Comment by gurcei** [comment]
Aah, 'this' in the current context is 'having to format via the MEGA65 (and not via your PC's formatting utility).

But I see how a reader might not be able to make that connection, since we have an entire paragraph of text between that bolded statement's advice, and this reason why.

To help make it more explicit, I'm adding another bold sentence, in the user's voice ("I"), let's see how that goes:
![image](https://user-images.githubusercontent.com/20013309/139586682-91c61cdd-ebbc-4a5f-9810-2ada360c1c3a.png)
