### ISSUE TITLE
Support Files, incorrect link

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#400]
http://mega65.org/sdcard-files suppose to bring you to the full (incl ROM) file, not to the "no-ROM" file as the text suggests:

![Screenshot 2021-10-30 at 17 36 36](https://user-images.githubusercontent.com/75681098/139539791-3d797388-b347-4f18-bde8-bd4f53690dd6.jpg)

**Comment by MauriceMEGA65** [comment]
Update: am I reviewing an older version of the manual? It states 29 October, but I doubt it's correct

**Comment by gurcei** [comment]
I've got a fix for this in a pending PR which I'll hopefully finalise within a few hours from now. The issue you found was due to us hiding some nexys-related advice about where to get essentials no-rom (for the printed manual), but we didn't hide enough of that text. In my PR, I've hidden all of it.

**Comment by gurcei** [comment]
Ok, my PR is merged in, and the page now looks like this, think we're sorted on this now:
![image](https://user-images.githubusercontent.com/20013309/139583141-93f798e8-0b81-4333-9194-fbb68a19e6b0.png)
