### ISSUE TITLE
Chapter Input Devices; correct screenshot (JOYSTICK PORT vs CONTROLLER PORT)?

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#401]
Please verify if this is the latest screenshot from the Freezer. If I'm not mistaken, the Joystick ports have been renamed.

![Screenshot 2021-10-30 at 17 46 33](https://user-images.githubusercontent.com/75681098/139540145-42f0b6f9-0aaa-4160-a03d-61d4f6e0c4b5.jpg)

**Comment by gurcei** [comment]
At present, in mega65-core's `development` branch, they still have the text above.

I also have memories of us discussing the possibility of switching them to say `controller`, but I don't know if we were 100% going ahead with that, I have a memory of putting the idea on m3wp's radar, but not hearing back from him on it. I'll try chase down that thread (was it discord or on another ticket here? Not sure as yet)

**Comment by gurcei** [comment]
And ok, the penny has dropped, the screen you refer to as the 'freezer' is not actually the freezer, but it's the `mega65-config` utility.

**Comment by gurcei** [comment]
Ok, and reflecting back on all our past discussions, I now see you had 2 ideas:

1) To add the word PORT into these field names (E.g., JOYSTICK **PORT** 1/2).
   - This was the one I pinged m3wp on but he didn't get back to me on this.
2) To swap the word JOYSTICK to be CONTROLLER (E.g., **CONTROLLER** **PORT** 1/2).

When I ponder this, I'm thinking we should just leave it as-is, due to lack of space in 40-column mode.
Adding both terms would cause overflow on lines like:
```
CONTROLLER PORT 1 AMIGA MOUSE DETECTION
```
I'm kinda hopeful that at least for C64-people, terms like 'joystick port' and 'controller port' are kinda synonymous, and people will get the idea.

And of the two, the term 'joystick port' actually seems more 'familiar' to my ears (even though admittedly, yes, the port can take other devices apart from joysticks).

So my suggestion is we leave it as-is for now. If we get a sense other people resonate with your concern on this, we can re-open this ticket.
