### ISSUE TITLE
bottom or centre align megakey contents

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#422]
Some megakeys get drown in a vertical top-aligned fashion, which looks a little unslightly, such as the arrows here:

![image](https://user-images.githubusercontent.com/20013309/140042524-2db72947-f567-4f28-8bc3-7e4f82ac06ca.png)

We had some chatter on discord about it here:
https://discord.com/channels/719326990221574164/720355877701550131/905348322724810783

It's something we can sort out for future editions of the manual, just leaving this ticket as a reminder.

**Comment by lydon42** [comment]
Going by the Keyboard:
Left and Up should be left/top aligned, because they are not cursor keys.
Down and Right are cursor keys and therefor should be centered.
The curly arrow head is wrong for both.

Observe #443 when fixing this.

**Comment by Impakt** [comment]
From memory I touched up the keys during my proof read, but i couldn't get them to look 100% the same as the keyboard.

**Comment by lydon42** [comment]
I think the main problem is that you can't distinguish the left arrow from cursor left or the up arrow from cursor up.
Also in all matrix tables, there is essentially no cursor left and up, because they don't exists.

**Comment by Impakt** [comment]
They’re coloured differently

**Comment by lydon42** [comment]
I don't see that in the latest manual build:
![matrix2](https://user-images.githubusercontent.com/16632479/172812217-707dc81e-8715-4045-981d-0a4d807bcb94.jpg)
![matrix](https://user-images.githubusercontent.com/16632479/172812223-7960609a-518c-4df6-ace6-1d28d41b01f0.jpg)

**Comment by Impakt** [comment]
> I don't see that in the latest manual build:

Is that screenshot from the user guide?

**Comment by dansanderson** [comment]
Based on what I could read from prior discussion, vertically centering megakey was non-controversial, it was just paused due to the UG1 production schedule. I did an audit and some clean-up of keycap markup. Resolving this as fixed.

If we want to reconsider arrow vs. cursor key styling, we can start a new conversation.

![CleanShot 2024-07-09 at 19 43 58](https://github.com/MEGA65/mega65-user-guide/assets/408973/4e3ee81b-88d5-4215-b1e2-ccbc5fee52c7)

(Note that this screenshot also looks different because I updated our monospace font a while back, and corrected the specific keycap markup in this table.)
