### ISSUE TITLE
Invalid UTF-8 byte

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-user-guide#45]
This is not an important issue, but an interesting one (at least for me :-)

The file "userguide.log" shows 135 lines with this error message:
Invalid UTF-8 byte or sequence at line nnn replaced by U+FFFD.

I located the source of these error messages in the file "xstring.tex".
/opt/local/share/texmf-texlive/tex/generic/xstring/xstring.tex

This file was created by Christian Tellechea, who used french characters in
his comments, which are coded in Latin1, not in UTF8.
One could expect, that this should not be regarded as an error, because all of
these characters are in comments, but LaTeX prints these errors.

I contacted Christian Tellechea and asked him, if he knows a solution
(hoping he would convert his file to UTF8). He replied, that he was aware of this
problem, but would neither convert his file nor renounce using french characters.

I tried to silence the warnings using the {silence} package, but this is unsuitable
in the phase, where the packages, like {xstring} are read in.

Well, this is less important, but I tried to reduce the messages in the log file,
so that the important error messages are easier to locate.
Maybe someone of you has an idea?

**Comment by gardners** [comment]
What's the license on his file?  I understand the French desire to not have to compromise their characters, but UTF8 is purposely supporting all languages, and doesn't support Latin-1 encoding, because, well, it's a different encoding. Same applies to putting German umlauts etc, so it isn't a French-specific problem, as far as I am aware. If it is open-source, we can simply make a copy and modify it to UTF8-ise the comments, preserving the visual presentation of the comments, and use that local copy, instead of the installed copy.

**Comment by Edilbert** [comment]
I followed your proposal and included a local copy in UTF-8 encoding.
