### ISSUE TITLE
EDMA DMA command byte can be used to set copy direction etc, but this is not documented

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#518]
**Describe where we can find the problematic topic**

EDMA documents only the function of the bottom two bits of the command argument.

**Describe the solution you'd like**

All bits should be documented, especially the copy direction and address hold bits, so that users can see how to use these functions from BASIC.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by nobruinfo** [comment]
@gardners From the discussion in [Discord](https://discord.com/channels/719326990221574164/886188425143799818/1055441470426980432) I was only able to learn that there is direction aswell. This and what's in the BASIC reference guide to me makes:

```
| 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
|   |   | d |   |   |   | c | c |

cc
00 copy
01 mix
10 swap
11 fill

d
1  direction
```

My sources were BASIC book, section on EDMA command and the Mega65 book chapters **F018A/B DMA JOBS** and the followings. I'm assuming F018B mode is used by BASIC.

The BANK and FLAGS table is confusing me. LGBs example used Bit 5 to set the direction and his screenshot shows it to work with the cmd value of 32. The table says Bit 6 which would be 64.

Of course this has no priority. The M65 does so much, it is simply impossible to have the doc at a hundred percent. Thank you for a reply somewhen in the future.

**Comment by lgblgblgb** [comment]
And finally, indeed it can be useful as mentioned on Discord, to mark the `DMA` command clearly as a legacy which has inconsistent parameter list syntax even between different C65/ROM versions, so better not to use that, and only here for compatibility with BASIC10. In this way, I guess even an example may be omitted for `DMA` and focusing on `EDMA` more. At least this is my idea and feeling about this.

**Comment by nobruinfo** [comment]
> &hellip;mark the DMA command clearly as a legacy&hellip;

@lgblgblgb Thank you very much for elaborating. The DMA is already properly marked.

> &hellip;first big table on the page, DST_DEC and SRC_DEC fields&hellip;

Your table is much more explanatory than what's in the book. Now I understand one actually can use bit 5 or bit 6 (adding 32, 64 respectively) to make things reverse. Setting both bits would probably make look the output is if no bits were set, although the routine still working backwards. Nice.

> &hellip;whole byte is maybe used&hellip;

It much seems exactly just like this. Here's what we could do for BASIC usage:

1. Keep things simple by only keep all the commands (bits 0, 1) and documenting bit 5 as a reversing possibility.
2. Warning for that the rest of the bits also have function and refering to the DMA chapter of the books.

> &hellip;some BASIC example can be useful&hellip;

Saw you on Discord and this helped me a lot. Well, it may look like this only if you first put a border to have `ClrScrn` not make the output appear in the upper left corner, above the listing so to speak. I might adapt this ever so slightly.

It now will take me some time because there is an already existing pull request and other things on various pages.

**Comment by nobruinfo** [comment]
@lgblgblgb I also like this self-contained approach. Maybe we could shift the listing below the output or make two screens.

However, in the books this anyway looks much different there are no screens and the listings are always text. This makes it handy to copy the whole listing. Xemu has phantastic clipboard functionalities so we have it up and running in no time. :)

**Comment by nobruinfo** [comment]
@lgblgblgb I'm going to hand in this as a pull request: [EDMA #518 pages from mega65-basic65-reference.pdf](https://github.com/MEGA65/mega65-user-guide/files/10295005/EDMA.518.pages.from.mega65-basic65-reference.pdf)

There is a queue so you won't have it in the manuals for another while.
