### ISSUE TITLE
Missing Keys/Keycodes in the Key Combination Tables

### ISSUE THREAD

**Issue by y0014984** [MEGA65/mega65-user-guide#532]
**Describe where we can find the problematic topic**

Where: Appendix D: The MEGA65 Keyboard - Headline "Key Combination Tables"; TeX File appendix-keyboard.tex; Line numbers 63 to 86; seems to be embedded content? https://github.com/MEGA65/mega65-user-guide/blob/2882cb8a1137390e4f620df3e5c4a7de5b5ba3ce/appendix-keyboard.tex#LL56-L56C36

What: The 5 Key Combination Tables have entries for arrow keys. The right arrow and the down arrow keys with their codes seem to refer to the cursor keys on the left side of the keyboard. The left and the up arrow key and the correspondig codes seem to refer to the arrow symbol keys, one on the far left and one near the return key. This leads to 2 problems:
1: The left ($9d when keypress is unmodified) and up ($91 whren keypress is unmodified) arrow cursor keys are not present in this list. They should be added because I think they are highly used.
2: The cursor and the symbol keys should be clearly distinguishable in the list, either graphically or using an asterisk and explaination. The user's guide on page 13 used black font on white keys for the symbol keys and white font on black keys for the arrow keys.

**Describe the solution you'd like**

1. Adding the missed curosr keys 
2. Make symbol and cursor keys distinguishable
(I would create a pull request but I don't understand the mechanism with the embedded minipages for the tables and can't find the linked/embedded content)

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by dansanderson** [comment]
I updated the markup in the keymaps to correctly use the black-on-white for the up-arrow and left-arrow symbol keys. https://github.com/MEGA65/mega65-user-guide/commit/e60d976f4dac3d6f51d79fffb6f0536ace04c6c8

There's an understandable confusion here: Of the cursor keys, only cursor-right and cursor-down are represented in the keymaps, because from the keyboard's perspective, cursor-up is Shift + cursor-down, and cursor-left is Shift + cursor-right. In addition to that, there are up-arrow and left-arrow symbol keys. Hopefully making their appearance similar to the rest of the books resolves at least part of the confusion.
