### ISSUE TITLE
Review remarks: User Guide 2nd edition, version 15 September

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#563]
Amazing work, I really like the improvements made!

My remarks:

**Page 5 - Side Connections**

In picture, add the preferred mouse connector. Ie:
CONT PORT 1 - MOUSE / JOYSTICK 2
CONT PORT 2 - JOYSTICK 1

**Page 18 - RESTORE**

In the RESTORE chapter, the last link to page 26 (Freezer) does not correctly work. It links to page 24.
Update: seems more links are not working for me. Please check the links.

**Page 19/20**

“ARROW KEYS” is written in capitals, while “Function Keys” is not(?)

**Page 28 - GO64 Mode**

Why a link to “thefuturewas8bit.com”? Seems out of place to link to a commercial third party. Also, there are other alternative SD2IEC devices out there.

**Page 63 - DD vs HD Disks**

Can “VS.” Be written in full (“versus”)? Combined with “DD” and “HD” there are just too many abbreviations in one title.

**Page 66 - Auto-booting disks**

The community disk contains “BASIC65.D81” which contains all the BASIC examples. It also has an “AUTOBOOT.C64” example on it. You can refer to it if you like.

**Page 89**

Add a comma in this sentence:
“Note: The ↑ character used for exponentiation is entered with ………”

**Page 115 - COLOR**

COLOR is obsolete per ROM 920338 and replaced by FOREGROUND. You can remove this command.
See Github issue #535
Looks like both COLOR and FOREGROUND are in the ROM, but BitShifter mentioned COLOR should be removed (?).

**Page 134 - EDIT**

I wrote a note for myself: “see INPUT#”.
Because EDIT can be used to make files that are readable by INPUT#.
Perhaps good to make a note in the manual?

**Page 136 - EDMA**

Thanks for the added example. I have added it to BASIC65.D81

**Page 148 - FONT**

No remarks, besides: thanks for improving the text. Much clearer now!

**Page 158 - GOTO**

The example contains an error. What happened: GOSUB example is used, in line 110 the GOSUB is exchanged to GOTO. Rest of the program is identical. Running the program ends in and error (return without gosub).
If you have a better example I’m all for it.

**Page 191- PALETTE**

Not sure about it, but I remember PALETTE also needs to be used when defining colors above 31 (on top of the default palette 0-31). If this is true, perhaps good to mention it here.

**Page 215 - RREG**

The example mentioned in the manual is obsolete and replaced by the one you can find on BASIC65.D81 (latest one, on Filehost)

**Page 243 - USR**

The example mentioned in the manual is obsolete and replaced by the one you can find on BASIC65.D81 (latest one, on Filehost)
But please update POKEW to WPOKE in line 10. I have BASIC65.D81 updated, but not yet put on Filehost

**Page 254 - CHR$**

In the table, is it possible to add another column for the ASCII characters of FONT A?
So for CHR 92 ( \ ), 94 (^), 95 (_), 123 ({), 124 (|), 125 (}), 126 (~)

**Last page - Quick Reference Card**

Card rotated by 90 degrees and hard to read. Please make landscape again.
Also, is it possible to add:
 GO64 / SYS 58552
 Shortcuts for the disk commands

**Comment by dansanderson** [comment]
Thanks very much for the detailed review!

Re: preferred mouse port: Starting with v0.96, the mouse (and paddles) will work in both ports.

Re: internal links, they're working for me in macOS Preview. It would be odd for them not to work because they are generated by LaTeX. If you can reproduce this, which PDF viewer and operating system are you using?

Re: COLOR: "COLOR ON/OFF" has been removed from the ROM and the manual. "COLOR number" is still an alias for FOREGROUND.

Re: adding ASCII to the PETSCII table: The FONT entry has the ASCII character table, including the codes. Several tables currently found around the BASIC reference ought to move to their own appendices (e.g. system palette is currently buried with BACKGROUND), and I can imagine moving the ASCII character table as well. I also want a screen code table. Right now I'm balancing further production work against hitting a print deadline, so it might not be in the 2nd edition, but it's on my mind.

Re: quick reference card: It appears in portrait orientation for the purposes of online use of the PDF. We'll make sure this gets printed landscape, just like last time.

All other feedback incorporated. Thanks again!
