### ISSUE TITLE
FREEZER shortcomings not explained

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-user-guide#572]
The userguide does not explain the shortcomings of the FREEZERs freeze function (F7).

They are:
- Attic RAM is **not** frozen
- Disk images are restored by their filename, the path is not saved. So restore will only find images in the root (or current?) directory on the SD card

Solutions:
- if you want to freeze a program that depends on mounted disks, put the disk images into the root of your SD card
- don't freeze programs that use Attic RAM

**Comment by dansanderson** [comment]
This probably goes in the Memory chapter. We should make sure developers understand these limitations, and make it their responsibility to communicate to users of their program that the program can't be frozen (or some other workaround specific to the program). The User's Guide only covers freeze states in a short paragraph, and users have no way of knowing when a given program would be incompatible with the freezer limitations.

I'm revising the Memory chapter soon and will look for a place to mention it.

**Comment by dansanderson** [comment]
I added a note about Freezer not freezing Attic in the Memory chapter, as an advisory to programmers. It recommends that programmers subsequently advise users about freeze states as needed.

User's Guide 2nd edition has a prominent section and warning about the use of subdirectories that I believe resolves the concern (as best as documentation can, at least).

In general, Freezer deserves its own chapter in the User's Guide. I held off on this for UG2 because I'm hoping we will continue to develop and polish the Freezer experience. Once we have either completed or pruned unfinished features and generally feel good about the reliability and usability of the Freezer, we can write it up.
