### ISSUE TITLE
Spacing between chapters/paragraphs

### ISSUE THREAD

**Issue by dikdom** [MEGA65/mega65-user-guide#91]
Between the paragraphs there are ugly big spaces in the 'FORMATTING SD CARDS' chapter.
I get it that it is because the whole page should be filled, but I think it shouldn't. Check the previous chapter. ... and now I checked that also and found there problems too... 
- Are you sure that the THE CURSOR KEYS should not start right after the RESTORE chapter? In the generated pdf the RESTOR is a few lines only the the rest of the page is empty.
- And this 'You will get an effect something like:' and its figure - I think it also would fit into the previous page, it doesn't have to be broken to a new page..

**Comment by gardners** [comment]
This is all due to the LaTeX type-setting rules.  As I mentioned in another issue, there is often no perfect solution to these, without adding some extra text: If the paragraphs all go to the top of the page, then the reader may think its the end of a chapter or section, when it isn't. If they are spread out then as you mention, this isn't entirely visually satisfying much of the time, either.

If you'd like to take on the role of hunting for these, and proposing text to fix them, that would be most welcome. Similarly adding the \needspace{4cm} lines before sentences or paragraphs that precede images.  This would allow me to focus more on the content creation with my limited time.

**Comment by gurcei** [comment]
I think this kinda issue has been sorted out now due to us switching to raggedbottom, so closing this one.
