### ISSUE TITLE
FDISK/FORMAT utility naming

### ISSUE THREAD

**Issue by dikdom** [MEGA65/mega65-user-guide#92]
This utility is called on the screenshot as 'SDCARD FDISK+FORMAT UTILITY', in the text it is constantly referred as FDISK/FORMAT (utility). 
  
 \+ or / 

It is not a big deal and please discard this bug if you find this too cosmetic issue.

**Comment by gardners** [comment]
If you're willing to make a pull-request that harmonises it, we'd love to accept it:)

**Comment by gurcei** [comment]
Just for clarity, I believe this is the string being referred to:
![image](https://user-images.githubusercontent.com/20013309/132378987-d0b67c36-c42c-435b-a25d-e7e8a498bf1c.png)

Hmm, since Hyppo is quite space constrained, there might be merits in shortening this string to just "FDISK/FORMAT", but personally, I'm ok with the lengthier name.

**Comment by gurcei** [comment]
In more recent versions, we've provided text to make the association between the two terms better:
![image](https://user-images.githubusercontent.com/20013309/139827642-1c955591-01ed-44c6-aef9-fc0f16cc890b.png)

So feel like we've got this sorted now.
