### ISSUE TITLE
Format SD screenshot

### ISSUE THREAD

**Issue by dikdom** [MEGA65/mega65-user-guide#93]
On the page 27 of the pdf, again there is big spaces between paragraphs.

And the text says: 'If you have only an internal SD card'
But in the screenshot next to it, we can see how does it look like when there is only an *external* SD card in the system. Please fix either the text of the screenshot.

Just a question: do you really have to select the BUS when there is only one SD card detected? What happens when there is no SD card detected?

**Comment by gardners** [comment]
The big spaces between the paragraphs is due to the typesetting rules deciding it would have looked worse if it tied to squish more onto the page, e.g., because a screen shot follows that doesn't fit.  These can be tricky to fix satisfactorily. Often, the best solution is to add an extra paragraph of explanatory text, so that the page fills up a bit more.  Which in this case seems a sensible option.

Again, if you can offer a pull-request that corrects the text/image mis-match, that would be super.

**Comment by gurcei** [comment]
Screenshots have been updated.

As for the spacing matter, it has bugged me a lot too. From the homework I've done on the matter, it stems from Latex defaulting to a style it calls `\flushbottom` (latex adds extra space to assure that content is spaced from top-to-bottom evenly on the page), whereas the style that my eyes are accustomed to is called `\raggedbottom` (if an item towards the bottom of the page doesn't fit, just move it to the next page and leave some space at the bottom of the previous page.

I decided to switch to the `\raggedbottom` style, added the setting into `common-header.tex`.

To my eyes, it has made things look much better, and I didn't get anybody complaining as yet, so I think it should be fine on that front.

Will close this card as it's sorted now.

I
