### ISSUE TITLE
CONFIGURING YOUR MEGA65

### ISSUE THREAD

**Issue by dikdom** [MEGA65/mega65-user-guide#95]
In this chapter there are large screenshots and understandable that those are moving the next page. But there is always a sentence referring to them, which stay at the previous page. This is rather annoying. Could you pair the corresponding sentence and screenshot to stay at the same page?

There is one more thing when describing the exit options, this is the last one:
'Save as Default and Exit'
This is not what on the Screenshot is present, in the image it is spelled: 'Defaults'. Is it possible to fix this string in the code (that Mega65 shall print 'Default' instead of 'Defaults')?

**Comment by gardners** [comment]
Yes, its possible to cause the preceding sentence or paragraph to the same page by using the \needspace{} latex macro, e.g., \needspace{4cm}, so that they can't appear on the end of a page.

I've fixed the defaults -> default message in the 138-hdmi-audio-27mhz branch, which will get merged in over time.  

We will still need an updated screen shot, so I'll leave this issue open until then.

**Comment by gurcei** [comment]
I think the situation has improved reasonably well since the ticket. The text-to-picture separation does occasionally happen still, but not as often.

Also, on the 2nd matter, we'll be switching the text in the manual to say 'Save as Defaults and Exit' (pluralised) and won't touch the text in the code, as it's nicer pluralised, I feel. There will be a PR tonight to sort this out, so will close this in anticipation of it.
