### ISSUE TITLE
microSD cards

### ISSUE THREAD

**Issue by dikdom** [MEGA65/mega65-user-guide#96]
In the chapter of INSTALLING AN UPGRADE CORE FOR THE MEGA65.

"The flash menu will preferentially use the external microSD slot over the internal SD card"

This is the first time that the document refers to microSD card or slot. In fact, in the chapter "GETTING TO KNOW YOUR MEGA65" there is only one SD card introduced. The external and it is clearly stated as an SD card (and not a microSD card).

- It would be good that in the introduction chapter the doc would mention that there is an option to have two SD cards installed (and if so, one of them is microSD card) and what are they used for..
- From this chapter I would leave the "microSD slot" reference as it is confusing (at least for me, as I don't know what is microSD and what is not...)

**Comment by gardners** [comment]
Thanks for you continued careful proof-reading! It is really helping the user guide to become better and better :)

There probably is still value in talking about microSD, because otherwise people might think they can shove a full-sized SD card in the back, when that isn't the case (but you can put it in the trap-door).

So probably the correct solution here is to fix the earlier introduction to talk about microSD cards, or at least indicate that it is a micoSD-sized SD card slot on the rear.

More generally, it would be great to get you setup with the means to make pull-requests containing your suggestions, so that we can more quickly incorporate them.  Have you made pull-requests in git before?
